### ISSUE TITLE
No highlighting for ctrlp.vim 

### ISSUE THREAD

**Issue by tricarte** [stefanvanburen/rams.vim#5]
Thank you for this simple but great looking colorscheme. I really love the light one. One issue though, there is no background highlighting for the selected item in ctrlp.vim. It's a real show stopper for me.

![no-highlight](https://user-images.githubusercontent.com/3023026/120752273-178afd00-c512-11eb-8a3e-729c35ff8136.png)

**Comment by stefanvanburen** [comment]
Would be happy to add the highlight groups for ctrlp - I don't use the plugin myself, but would accept a PR, or I can probably look into it early next week!

**Comment by stefanvanburen** [comment]
just installed https://github.com/ctrlpvim/ctrlp.vim and fired it up - it looks there's a little indicator arrow on the left that shows the current line. Will think about this more!

![image](https://user-images.githubusercontent.com/622527/120820797-de0ebd80-c522-11eb-87af-4c2028a471f3.png)

**Comment by tricarte** [comment]
OK, this is interesting. All of a sudden that indicator now shows up properly. I don't know why it didn't as in my screenshot but who cares. Now it works. Thank you again.

**Comment by stefanvanburen** [comment]
glad that helped! thanks for trying out the colorscheme!
